# Generated by Django 6.0.1 on 2026-01-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='tasks_high_prio_count',
            field=models.IntegerField(default=0),
        ),
    ]
