# Generated by Django 6.0.1 on 2026-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
