# Generated by Django 6.0.1 on 2026-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_boards_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
    ]
