# Generated by Django 6.0.1 on 2026-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_alter_boards_tasks_to_do_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardsDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True)),
                ('owner_id', models.IntegerField()),
                ('members', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
