# Generated by Django 6.0.1 on 2026-01-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0005_boards_tasks_high_prio_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='ticket_count',
        ),
    ]
