# Generated by Django 6.0.1 on 2026-01-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_boards_tasks_high_prio_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='ticket_count',
        ),
    ]
