# Generated by Django 6.0.1 on 2026-01-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_remove_boards_ticket_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='tasks_to_do_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
    ]
