# Generated by Django 6.0.1 on 2026-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_remove_boards_tasks_high_prio_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='tasks_high_prio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.IntegerField(default=0),
        ),
    ]
