# Generated by Django 6.0 on 2026-01-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_remove_boards_tasks_high_prio_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this board.', related_name='member_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='owner',
            field=models.ForeignKey(help_text='User who owns and created the board.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title of the board.', max_length=100, null=True),
        ),
    ]
